name: timesan
description: 'A Flutter game! Featuring time itself.'
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.14.0
  google_fonts: ^6.1.0
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  firebase_ui_auth: ^1.13.0
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: 1.2.17
  flutter_redux: ^0.10.0
  redux: ^5.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/ui/
    - assets/